name: Deploy Python App to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            sudo apt-get update -y
            sudo apt-get install -y python3 python3-pip          
            cd ~/my-python-app || mkdir ~/my-python-app && cd ~/my-python-app  
            git clone https://github.com/${{ github.repository }}
            pip3 install -r requirements.txt
            pkill -f "gunicorn" || true
            nohup gunicorn -b 0.0.0.0:5000 app:app > app.log 2>&1 &
    
        
      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            # Disable IPv6 to avoid network unreachable errors
            sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1
            sudo sysctl -w net.ipv6.conf.default.disable_ipv6=1

            sudo apt-get update -y
            sudo apt-get install -y python3 python3-pip

            cd ~/my-python-app || mkdir ~/my-python-app && cd ~/my-python-app  
            if [ ! -d .git ]; then
              git clone https://github.com/${{ github.repository }} .
            else
              git pull
            fi

            pip3 install -r requirements.txt
            pkill -f "gunicorn" || true
            nohup gunicorn -b 0.0.0.0:80 app:app > app.log 2>&1 &
          EOF

          
