name: Deploy Python App to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: | 
              ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
              sudo apt-get update -y
              sudo apt-get install -y python3 python3-pip
              rm -rf ~/Python-Application

              git clone https://github.com/${{ github.repository }} ~/Python-Application

              cd ~/Python-Application

              pip3 install -r requirements.txt

              pkill -f "python3 app.py" || true

              nohup python3 app.py > app.log 2>&1 &
              EOF
